name: Publish Docker Image(clash tun mode)
on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - config.yaml
      - docker-compose.yml
      - README.md
      - LICENSE
jobs:
  build:
    name: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get names of branch and tag
        id: vars
        run: |
          echo ::set-output name=branch::${GITHUB_REF##*/}
          echo ::set-output name=tag::${GITHUB_REF##*/}
      - name: Generate Docker image tag/0
        uses: haya14busa/action-cond@v1
        id: docker_image_tag
        with:
          cond: ${{ steps.vars.outputs.branch == 'master' }}
          if_true: "rinex20/docker-clash-tun:latest"
          if_false: "rinex20/docker-clash-tun:${{ steps.vars.outputs.tag }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_image_tag.outputs.value }}
